apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
  labels:
    app: techtrends
spec:
  selector:
    matchLabels:
      app: techtrends
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - name: techtrends
          image: {{ .Values.containers.image.repository }}:{{ .Values.containers.image.tag }}
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          ports:
            - containerPort: 3111
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              host: ''
              path: {{ .Values.containers.livenessProbe.path }}
              port: {{ .Values.containers.livenessProbe.port }}
              scheme: ''
          readinessProbe:
              httpGet:
                host: ''
                path: {{ .Values.containers.readinessProbe.path }}
                port: {{ .Values.containers.readinessProbe.port }}
                scheme: ''