namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

replicaCount: 1

image:
  repository: testabro/techtrends
  tag: latest
  imagePullPolicy: IfNotPresent
  terminationMessagePolicy: File

  ports:
    - containerPort: 3111
  
  resources:
    requests:
      cpu: 250m
      memory: 64Mi
    limits: 
      memory: 128Mi
      CPU: 500m

  livenessProbe:
    httpGet:
      host: ''
      path: /healthz
      port: 3111
      scheme: ''
  readinessProbe:
    httpGet:
      host: ''
      path: /healthz
      port: 3111
      scheme: ''
