namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

replicaCount: 1

ports:
  containerPort: 3111

image:
  repository: testabro/techtrends
  tag: latest
  imagePullPolicy: IfNotPresent
  terminationMessagePolicy: File

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits: 
    memory: 128Mi
    CPU: 500m

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111